# Generated by Django 4.2.6 on 2023-10-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sasvar_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="residuo",
            name="title",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="residuo",
            name="imagen",
            field=models.ImageField(upload_to="sasvar_app/images"),
        ),
    ]
