# Generated by Django 4.2.6 on 2023-10-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sasvar_app", "0002_residuo_title_alter_residuo_imagen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Waste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("imagen", models.ImageField(upload_to="storage")),
                ("img_name", models.CharField(max_length=50)),
                ("waste_type", models.IntegerField()),
                ("container_id", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(name="Residuo",),
    ]
