# Generated by Django 4.2.6 on 2023-10-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sasvar_app", "0003_waste_delete_residuo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waste",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
