# Generated by Django 4.2.6 on 2023-10-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sasvar_app", "0004_alter_waste_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waste",
            name="imagen",
            field=models.ImageField(upload_to="sasvar_app/images"),
        ),
    ]
