# Generated by Django 4.2.4 on 2023-11-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasvar_app', '0006_waste_model_version_alter_waste_container_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='model_version',
            field=models.CharField(default='app_model_V0-T23', max_length=50),
        ),
    ]
